import { AgentTemplate } from "./template-card";

export const agentTemplates: AgentTemplate[] = [
  // Customer Support Templates
  {
    id: "customer-support-general",
    name: "Customer Support Agent",
    description: "Handle general customer inquiries, troubleshoot issues, and provide product information with empathy and efficiency.",
    category: "Customer Support",
    icon: "headphones",
    industry: "General",
    features: ["FAQ Handling", "Issue Escalation", "Ticket Creation", "Knowledge Base Access"],
    tools: ["knowledge_base", "create_ticket", "transfer_call", "send_email"],
    complexity: "basic",
    estimated_setup_time: "5 min",
    popularity: 2450,
    is_new: false,
    is_featured: true,
    sample_greeting: "Hello! Thank you for calling. My name is Alex, and I'm here to help you today. How can I assist you?",
    sample_prompt: "You are a helpful customer support agent. Be empathetic, patient, and solution-oriented. Always try to resolve the customer's issue on the first call. If you cannot resolve the issue, offer to create a support ticket or transfer to a specialist.",
    use_cases: ["Product inquiries", "Order status checks", "Technical troubleshooting", "Complaint handling"],
  },
  {
    id: "technical-support",
    name: "Technical Support Specialist",
    description: "Provide advanced technical assistance, troubleshoot complex issues, and guide users through solutions step by step.",
    category: "Customer Support",
    icon: "headphones",
    industry: "Technology",
    features: ["Step-by-Step Guidance", "Remote Diagnostics", "System Checks", "Documentation Access"],
    tools: ["knowledge_base", "run_diagnostic", "create_ticket", "screen_share_request"],
    complexity: "intermediate",
    estimated_setup_time: "10 min",
    popularity: 1820,
    is_new: false,
    is_featured: false,
    sample_greeting: "Hi there! This is Tech Support. I understand you're having some technical difficulties. Let me help you get that sorted out.",
    sample_prompt: "You are an expert technical support specialist. Guide users through troubleshooting steps clearly and patiently. Verify each step before moving to the next. If the issue persists, escalate appropriately.",
    use_cases: ["Software issues", "Hardware troubleshooting", "Network problems", "Account access"],
  },

  // Sales Templates
  {
    id: "sales-inbound",
    name: "Inbound Sales Agent",
    description: "Convert inbound leads into customers by understanding needs, presenting solutions, and handling objections professionally.",
    category: "Sales",
    icon: "phone",
    industry: "General",
    features: ["Lead Qualification", "Product Demos", "Pricing Discussion", "CRM Integration"],
    tools: ["check_inventory", "calculate_quote", "schedule_demo", "update_crm"],
    complexity: "intermediate",
    estimated_setup_time: "10 min",
    popularity: 1950,
    is_new: false,
    is_featured: true,
    sample_greeting: "Thank you for your interest in our products! I'm Sarah, your sales specialist. I'd love to learn more about what you're looking for today.",
    sample_prompt: "You are a consultative sales professional. Focus on understanding the customer's needs before presenting solutions. Use open-ended questions to qualify leads. Handle objections with empathy and data-driven responses.",
    use_cases: ["Product inquiries", "Pricing requests", "Feature comparisons", "Demo scheduling"],
  },
  {
    id: "sales-outbound",
    name: "Outbound Sales Caller",
    description: "Proactively reach out to prospects, qualify leads, and set appointments for your sales team.",
    category: "Sales",
    icon: "phone",
    industry: "General",
    features: ["Cold Calling Scripts", "Appointment Setting", "Lead Scoring", "Follow-up Scheduling"],
    tools: ["check_calendar", "schedule_meeting", "update_crm", "send_email"],
    complexity: "advanced",
    estimated_setup_time: "15 min",
    popularity: 890,
    is_new: true,
    is_featured: false,
    sample_greeting: "Hi, this is Mike from [Company]. I'm reaching out because I noticed you recently [trigger event]. Do you have a moment to chat?",
    sample_prompt: "You are an outbound sales representative. Be respectful of people's time, quickly establish value, and aim to schedule a follow-up meeting with qualified prospects. Handle rejection gracefully.",
    use_cases: ["Lead generation", "Appointment setting", "Follow-up calls", "Market research"],
  },

  // Scheduling Templates
  {
    id: "appointment-scheduler",
    name: "Appointment Scheduler",
    description: "Efficiently book, reschedule, and manage appointments with smart calendar integration and conflict resolution.",
    category: "Scheduling",
    icon: "calendar",
    industry: "General",
    features: ["Calendar Sync", "Availability Check", "Reminders", "Multi-timezone Support"],
    tools: ["check_availability", "book_appointment", "send_reminder", "reschedule"],
    complexity: "basic",
    estimated_setup_time: "5 min",
    popularity: 3200,
    is_new: false,
    is_featured: true,
    sample_greeting: "Hello! I can help you schedule an appointment. What day and time works best for you?",
    sample_prompt: "You are a professional appointment scheduler. Efficiently find suitable times that work for both parties. Confirm all details including date, time, location/meeting link, and any preparation needed.",
    use_cases: ["Doctor appointments", "Consultations", "Service bookings", "Meeting scheduling"],
  },
  {
    id: "restaurant-reservation",
    name: "Restaurant Reservation Agent",
    description: "Handle table reservations, special requests, and dietary requirements for dining establishments.",
    category: "Scheduling",
    icon: "utensils",
    industry: "Hospitality",
    features: ["Table Management", "Special Requests", "Dietary Notes", "Waitlist Management"],
    tools: ["check_availability", "book_table", "add_waitlist", "send_confirmation"],
    complexity: "basic",
    estimated_setup_time: "5 min",
    popularity: 1450,
    is_new: false,
    is_featured: false,
    sample_greeting: "Thank you for calling [Restaurant Name]. I'd be happy to help you make a reservation. For what date and how many guests?",
    sample_prompt: "You are a friendly restaurant host. Help guests make reservations efficiently. Ask about party size, date, time preferences, and any special occasions or dietary requirements.",
    use_cases: ["Table bookings", "Special events", "Group reservations", "Takeout orders"],
  },

  // Healthcare Templates
  {
    id: "medical-receptionist",
    name: "Medical Office Receptionist",
    description: "Handle patient scheduling, insurance verification, and general inquiries for medical practices.",
    category: "Healthcare",
    icon: "stethoscope",
    industry: "Healthcare",
    features: ["HIPAA Compliant", "Insurance Verification", "Appointment Management", "Patient Records"],
    tools: ["check_schedule", "verify_insurance", "book_appointment", "send_reminder"],
    complexity: "intermediate",
    estimated_setup_time: "15 min",
    popularity: 1680,
    is_new: false,
    is_featured: true,
    sample_greeting: "Thank you for calling [Practice Name]. This is a confidential call. How may I help you today?",
    sample_prompt: "You are a medical office receptionist. Maintain strict HIPAA compliance. Help patients schedule appointments, verify insurance, and answer general questions. Never provide medical advice.",
    use_cases: ["Appointment scheduling", "Insurance questions", "Prescription refills", "Test results pickup"],
  },
  {
    id: "pharmacy-assistant",
    name: "Pharmacy Assistant",
    description: "Handle prescription refill requests, medication inquiries, and pharmacy hours information.",
    category: "Healthcare",
    icon: "stethoscope",
    industry: "Healthcare",
    features: ["Refill Requests", "Drug Information", "Insurance Check", "Pickup Scheduling"],
    tools: ["check_prescription", "request_refill", "verify_insurance", "schedule_pickup"],
    complexity: "intermediate",
    estimated_setup_time: "10 min",
    popularity: 920,
    is_new: true,
    is_featured: false,
    sample_greeting: "Thank you for calling [Pharmacy Name]. How can I assist you with your prescription needs today?",
    sample_prompt: "You are a pharmacy assistant. Help customers with prescription refills and general pharmacy inquiries. Verify patient information securely. Do not provide medical advice or drug interactions - refer to pharmacist.",
    use_cases: ["Refill requests", "Pickup scheduling", "Hours and location", "Transfer requests"],
  },

  // Real Estate Templates
  {
    id: "real-estate-agent",
    name: "Real Estate Assistant",
    description: "Qualify property leads, schedule viewings, and provide property information to potential buyers and renters.",
    category: "Real Estate",
    icon: "home",
    industry: "Real Estate",
    features: ["Lead Qualification", "Property Search", "Viewing Scheduling", "Market Information"],
    tools: ["search_properties", "schedule_viewing", "send_listing", "qualify_lead"],
    complexity: "intermediate",
    estimated_setup_time: "10 min",
    popularity: 1340,
    is_new: false,
    is_featured: false,
    sample_greeting: "Hello! Thank you for your interest in finding your perfect property. I'm here to help. Are you looking to buy or rent?",
    sample_prompt: "You are a real estate assistant. Qualify leads by understanding their property requirements, budget, timeline, and preferred locations. Schedule viewings and provide relevant property information.",
    use_cases: ["Property inquiries", "Viewing scheduling", "Market questions", "Lead qualification"],
  },

  // E-commerce Templates
  {
    id: "ecommerce-support",
    name: "E-commerce Support Agent",
    description: "Handle order inquiries, returns, shipping questions, and product recommendations for online stores.",
    category: "E-commerce",
    icon: "shopping",
    industry: "Retail",
    features: ["Order Tracking", "Returns Processing", "Product Recommendations", "Inventory Check"],
    tools: ["track_order", "process_return", "check_inventory", "apply_discount"],
    complexity: "basic",
    estimated_setup_time: "8 min",
    popularity: 2100,
    is_new: false,
    is_featured: true,
    sample_greeting: "Welcome to [Store Name] customer service! I can help you with orders, returns, or finding the perfect product. How can I assist you?",
    sample_prompt: "You are an e-commerce support specialist. Help customers track orders, process returns, check product availability, and make personalized recommendations based on their needs.",
    use_cases: ["Order status", "Return requests", "Product questions", "Shipping inquiries"],
  },

  // Travel Templates
  {
    id: "travel-booking",
    name: "Travel Booking Assistant",
    description: "Help travelers book flights, hotels, and create personalized travel itineraries.",
    category: "Travel",
    icon: "plane",
    industry: "Travel",
    features: ["Flight Search", "Hotel Booking", "Itinerary Planning", "Travel Insurance"],
    tools: ["search_flights", "book_hotel", "create_itinerary", "check_visa"],
    complexity: "advanced",
    estimated_setup_time: "15 min",
    popularity: 780,
    is_new: true,
    is_featured: false,
    sample_greeting: "Hello! Ready to plan your next adventure? I can help you find flights, hotels, and create the perfect itinerary. Where would you like to go?",
    sample_prompt: "You are a travel booking assistant. Help customers plan trips by understanding their destination, dates, budget, and preferences. Provide relevant options and make the booking process seamless.",
    use_cases: ["Flight bookings", "Hotel reservations", "Trip planning", "Travel inquiries"],
  },

  // Automotive Templates
  {
    id: "auto-dealership",
    name: "Auto Dealership Assistant",
    description: "Handle vehicle inquiries, schedule test drives, and provide financing information for car dealerships.",
    category: "Sales",
    icon: "car",
    industry: "Automotive",
    features: ["Inventory Search", "Test Drive Scheduling", "Financing Calculator", "Trade-in Estimates"],
    tools: ["search_inventory", "schedule_test_drive", "calculate_payment", "estimate_trade"],
    complexity: "intermediate",
    estimated_setup_time: "10 min",
    popularity: 650,
    is_new: false,
    is_featured: false,
    sample_greeting: "Thank you for calling [Dealership Name]. Looking for a new vehicle? I can help you find the perfect car and schedule a test drive.",
    sample_prompt: "You are an auto dealership assistant. Help customers find vehicles matching their needs and budget. Schedule test drives and provide financing estimates. Be knowledgeable but not pushy.",
    use_cases: ["Vehicle inquiries", "Test drives", "Financing questions", "Service scheduling"],
  },

  // Education Templates
  {
    id: "university-admissions",
    name: "University Admissions Assistant",
    description: "Answer prospective student questions about programs, admissions requirements, and campus life.",
    category: "Education",
    icon: "graduation",
    industry: "Education",
    features: ["Program Information", "Application Status", "Campus Tours", "Financial Aid"],
    tools: ["search_programs", "check_application", "schedule_tour", "calculate_aid"],
    complexity: "intermediate",
    estimated_setup_time: "12 min",
    popularity: 540,
    is_new: true,
    is_featured: false,
    sample_greeting: "Welcome to [University Name] admissions! I'm here to answer your questions about our programs and help you with the application process.",
    sample_prompt: "You are a university admissions assistant. Provide accurate information about programs, requirements, deadlines, and campus life. Be encouraging and helpful to prospective students.",
    use_cases: ["Program inquiries", "Application help", "Tour scheduling", "Financial aid questions"],
  },

  // Financial Services Templates
  {
    id: "banking-support",
    name: "Banking Support Agent",
    description: "Handle account inquiries, transaction questions, and basic banking services securely.",
    category: "Financial",
    icon: "building",
    industry: "Financial Services",
    features: ["Account Verification", "Transaction History", "Card Services", "Transfer Assistance"],
    tools: ["verify_identity", "check_balance", "report_card", "transfer_funds"],
    complexity: "advanced",
    estimated_setup_time: "20 min",
    popularity: 890,
    is_new: false,
    is_featured: false,
    sample_greeting: "Thank you for calling [Bank Name]. For your security, I'll need to verify your identity. Can you please provide your account number?",
    sample_prompt: "You are a banking support agent. Prioritize security and verify customer identity before discussing account details. Help with common banking tasks while maintaining strict compliance with financial regulations.",
    use_cases: ["Balance inquiries", "Card issues", "Transfer help", "Account questions"],
  },

  // HR & Recruiting Templates
  {
    id: "hr-assistant",
    name: "HR Assistant",
    description: "Handle employee inquiries about benefits, policies, and general HR questions.",
    category: "Customer Support",
    icon: "briefcase",
    industry: "Human Resources",
    features: ["Policy Information", "Benefits Questions", "Time Off Requests", "Directory Lookup"],
    tools: ["search_policies", "check_benefits", "submit_request", "lookup_employee"],
    complexity: "basic",
    estimated_setup_time: "8 min",
    popularity: 720,
    is_new: false,
    is_featured: false,
    sample_greeting: "Hello! This is HR Services. I can help you with questions about benefits, policies, or other HR matters. How can I assist you today?",
    sample_prompt: "You are an HR assistant. Help employees with questions about company policies, benefits, time off, and general HR inquiries. Maintain confidentiality and refer sensitive matters to HR specialists.",
    use_cases: ["Benefits questions", "Policy inquiries", "Time off requests", "Onboarding help"],
  },

  // Insurance Templates
  {
    id: "insurance-claims",
    name: "Insurance Claims Assistant",
    description: "Guide customers through the claims process and provide status updates on existing claims.",
    category: "Financial",
    icon: "heart",
    industry: "Insurance",
    features: ["Claim Filing", "Status Updates", "Document Requests", "Coverage Questions"],
    tools: ["start_claim", "check_claim_status", "request_document", "verify_coverage"],
    complexity: "intermediate",
    estimated_setup_time: "12 min",
    popularity: 680,
    is_new: false,
    is_featured: false,
    sample_greeting: "Thank you for calling [Insurance Company] claims department. I can help you file a new claim or check on an existing one. What would you like to do?",
    sample_prompt: "You are an insurance claims assistant. Guide customers through the claims process step by step. Collect necessary information accurately and set clear expectations about timelines and next steps.",
    use_cases: ["New claims", "Claim status", "Document submission", "Coverage verification"],
  },
];

export const templateCategories = [
  { id: "all", name: "All Templates", count: agentTemplates.length },
  { id: "Customer Support", name: "Customer Support", count: agentTemplates.filter(t => t.category === "Customer Support").length },
  { id: "Sales", name: "Sales", count: agentTemplates.filter(t => t.category === "Sales").length },
  { id: "Scheduling", name: "Scheduling", count: agentTemplates.filter(t => t.category === "Scheduling").length },
  { id: "Healthcare", name: "Healthcare", count: agentTemplates.filter(t => t.category === "Healthcare").length },
  { id: "E-commerce", name: "E-commerce", count: agentTemplates.filter(t => t.category === "E-commerce").length },
  { id: "Financial", name: "Financial", count: agentTemplates.filter(t => t.category === "Financial").length },
  { id: "Travel", name: "Travel", count: agentTemplates.filter(t => t.category === "Travel").length },
  { id: "Education", name: "Education", count: agentTemplates.filter(t => t.category === "Education").length },
  { id: "Real Estate", name: "Real Estate", count: agentTemplates.filter(t => t.category === "Real Estate").length },
];

export const templateIndustries = [
  "All Industries",
  "General",
  "Technology",
  "Healthcare",
  "Financial Services",
  "Retail",
  "Hospitality",
  "Real Estate",
  "Travel",
  "Education",
  "Automotive",
  "Insurance",
  "Human Resources",
];
